CREATE TABLE IF NOT EXISTS sede (
 id VARCHAR(64) PRIMARY KEY, nombre VARCHAR(120) NOT NULL CHECK (length(trim(nombre)) > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS sede_nombre_unico ON sede (lower(nombre));
CREATE TABLE IF NOT EXISTS estacionamiento (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 sede_id VARCHAR(64) NOT NULL REFERENCES sede(id),
 nombre VARCHAR(120) NOT NULL CHECK (length(trim(nombre)) > 0),
 capacidad INTEGER NOT NULL CHECK (capacidad BETWEEN 1 AND 10000),
 activo BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS estacionamiento_nombre_unico ON estacionamiento (sede_id, lower(nombre));
CREATE TABLE IF NOT EXISTS acceso (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 estacionamiento_id BIGINT NOT NULL REFERENCES estacionamiento(id) ON DELETE CASCADE,
 nombre VARCHAR(80) NOT NULL,
 tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('ENTRADA','SALIDA')),
 UNIQUE (estacionamiento_id, tipo), UNIQUE (id, estacionamiento_id, tipo)
);
-- Dispositivos preparados para integración futura; todavía no existe autenticación IoT.
CREATE TABLE IF NOT EXISTS dispositivo (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 acceso_id BIGINT NOT NULL REFERENCES acceso(id),
 codigo VARCHAR(80) NOT NULL UNIQUE, activo BOOLEAN NOT NULL DEFAULT TRUE,
 ultima_comunicacion TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS movimiento (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 evento_id UUID NOT NULL UNIQUE,
 estacionamiento_id BIGINT NOT NULL REFERENCES estacionamiento(id),
 acceso_id BIGINT NOT NULL,
 tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('ENTRADA','SALIDA')),
 origen VARCHAR(15) NOT NULL CHECK (origen IN ('MANUAL','SIMULADOR')),
 placa VARCHAR(12), registrado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (acceso_id, estacionamiento_id, tipo) REFERENCES acceso(id, estacionamiento_id, tipo)
);
CREATE INDEX IF NOT EXISTS movimiento_estacionamiento_idx ON movimiento(estacionamiento_id, registrado_en);
